name: homeserver tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: homeserver

    env:
      TF_VAR_cloudflare_account_id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      TF_VAR_cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      MINIO_ENDPOINT: ${{ secrets.MINIO_ENDPOINT }}
      MINIO_ACCESS_KEY: ${{ secrets.MINIO_ACCESS_KEY }}
      MINIO_SECRET_KEY: ${{ secrets.MINIO_SECRET_KEY }}

    steps:


      - name: Terraform test
        run: echo "Starting to run terraform tests"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Version
        run: terraform version
      
      - name: Create backend.hcl
        run: |
          cat > backend.hcl <<EOF
          bucket = "terraform-state"
          key = "homeserver/terraform.tfstate"
          endpoint = "${MINIO_ENDPOINT}"
          access_key = "${MINIO_ACCESS_KEY}"
          secret_key = "${MINIO_SECRET_KEY}"
          EOF
      - name: Terraform Init
        run: terraform init -backend-config=backend.hcl
      
      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        run: terraform plan

      - name: Terraform end
        run: echo "It seems like all worked"


      